version: '3.8'

services:
    backend:
      image: $IMAGE_DEV
      container_name: $CONTAINER_NAME
      environment:
        HOME: /app
        AWS_SDK_LOAD_NONDEFAULT_CONFIG: 1
        AWS_CONFIG_FILE: /app/.aws/config
        AWS_PROFILE: dev
        AWS_SDK_LOAD_CONFIG: 1

      working_dir: /app
      entrypoint: "npm start"
      volumes:
        - ./app:/app
        - ~/.ssh:/root/.ssh
        - ~/.aws/:/app/.aws/:rw
#      labels:
#        - "traefik.enable=true"
#        - "traefik.http.routers.frontend.rule=Host(`local.web-siri.com`) && PathPrefix(`/`)"
#        - "traefik.http.routers.frontend.priority=1"
#        - "traefik.http.services.frontend.loadbalancer.server.port=80"
      ports:
        - 80:80

services:
  backend:
    image: $IMAGE_DEV
    container_name: $CONTAINER_NAME
    entrypoint: "npm start"
    environment:
      VIRTUAL_HOST: 'siri.com'
      VIRTUAL_HOST_WEIGHT: 1
      HOME: /app
      AWS_SDK_LOAD_NONDEFAULT_CONFIG: 1
      AWS_CONFIG_FILE: /app/.aws/config
      AWS_PROFILE: dev
      AWS_SDK_LOAD_CONFIG: 1

    volumes:
        - ./app:/app
        - ~/.ssh:/root/.ssh
        - ~/.aws/:/app/.aws/:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`siri.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.backend.priority=1"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
    networks:
      - siri_network
networks:
  siri_network:
    external: true

